import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

type Lang = 'bg' | 'en';

interface LangCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  bg: {
    // Navbar
    'nav.home': 'Начало',
    'nav.services': 'Услуги',
    'nav.pricing': 'Цени',
    'nav.process': 'Процес',
    'nav.blog': 'Блог',
    'nav.contact': 'Контакти',
    'nav.help': 'Изпрати казус',
    'hero.call': 'Обади се',
    'nav.login': 'Вход',
    'nav.register': 'Регистрация',
    'nav.logout': 'Изход',
    'nav.lang': 'EN',

    // Hero
    'hero.title': 'Профилът ви е ',
    'hero.titleSpan': 'блокиран, ограничен или откраднат?',
    'hero.desc': 'Изпратете казуса си. До 24 часа ще получите първоначална оценка, реалистични опции и ясна следваща стъпка.',
    'hero.cta1': 'Изпратете казуса',
    'hero.cta2': 'Вижте как работим',
    'hero.stat2': 'Безплатна първоначална оценка',
    'hero.stat3': 'Не изпращайте пароли или кодове',
    'hero.badge1': 'Професионално обслужване',
    'hero.badge2': 'Всички платформи',
    'hero.badge3': 'Ясна комуникация',

    // Services section
    'svc.label': 'Какво правим',
    'svc.title': 'Цялостна ',
    'svc.titleSpan': 'защита',
    'svc.all': 'Всички услуги',
    'svc.s1.title': 'Възстановяване на акаунти',
    'svc.s1.desc': 'Баннати, спрени или ограничени акаунти в Instagram, TikTok, YouTube, Facebook.',
    'svc.s2.title': 'Премахване на shadowban',
    'svc.s2.desc': 'Диагностика и разрешаване на проблеми с невидимостта.',
    'svc.s3.title': 'Защита на съдържание',
    'svc.s3.desc': 'Превантивни одити и правни консултации.',
    'svc.s4.title': 'Спешна реакция',
    'svc.s4.desc': 'Приоритетно обслужване за спешни случаи.',
    'svc.s5.title': 'Откраднати профили',
    'svc.s5.desc': 'Възстановяване на хакнати и откраднати профили.',
    'svc.s6.title': 'Правни обжалвания',
    'svc.s6.desc': 'Професионална подготовка на документи и жалби.',

    // Process section
    'proc.label': 'Как работим',
    'proc.title': 'Процес на ',
    'proc.titleSpan': 'възстановяване',
    'proc.sub': 'От кратката заявка до ясна оценка и план за действие.',
    'proc.step1': 'Обработка на вашата заявка',
    'proc.step1desc': 'Индивидуална оферта според сложността на казуса.',
    'proc.step2': 'Подготовка на официална жалба',
    'proc.step2desc': 'Индивидуален план за действие.',
    'proc.step3': 'Изпращане по официални канали',
    'proc.step3desc': 'Директна комуникация.',
    'proc.step4': 'Следене на казуса ви',
    'proc.step4desc': 'До неговото разрешаване.',
    'proc.tag1': 'Безплатна оценка',
    'proc.tag2': 'Ясно проследяване',
    'proc.tag3': 'Дискретно обслужване',

    // Results section
    'res.label': 'Процес',
    'res.title': 'Ясни ',
    'res.titleSpan': 'параметри',
    'res.stat2': 'Обичаен първи отговор',
    'res.stat3': 'Поддържани платформи',

    // Testimonials
    'test.label': 'Отзиви',
    'test.title': 'Доверието на ',
    'test.titleSpan': 'клиенти',
    'test.q1': 'Възстановиха акаунта на марката ни за 72 часа. Невероятни!',
    'test.n1': 'Мария Петрова',
    'test.t1': 'Маркетинг директор',
    'test.q2': 'След месеци разочарование, възстановиха акаунта ми.',
    'test.n2': 'Иван Стоянов',
    'test.t2': 'Създател на съдържание',
    'test.q3': 'Професионални, бързи и дискретни. Препоръчвам!',
    'test.n3': 'Гергана Димитрова',
    'test.t3': 'Собственик на онлайн магазин',

    // CTA
    'cta.title': 'Разкажете ни какво се е случило',
    'cta.desc': 'Кратка форма, без задължения и без да споделяте пароли. Първи отговор до 24 часа.',
    'cta.btn1': 'Изпрати казуса',
    'cta.btn2': 'Виж цените',

    // Footer
    'foot.desc': 'Професионална оценка и съдействие при проблеми с дигитални акаунти.',
    'foot.services': 'Услуги',
    'foot.company': 'Компания',
    'foot.legal': 'Правна информация',
    'foot.rights': 'Всички права запазени.',
    'foot.privacy': 'Поверителност',
    'foot.terms': 'Общи условия',
    'foot.payments': 'Плащания',
    'foot.cookies': 'Настройки за бисквитки',

    // Services page
    'sp.hero.label': 'Услуги',
    'sp.hero.title': 'Експертни решения за ',
    'sp.hero.titleSpan': 'възстановяване',
    'sp.hero.desc': 'От възстановяване до проактивна защита — цялостни решения.',
    'sp.s1.title': 'Възстановяване на акаунти',
    'sp.s1.desc': 'Баннати, спрени или ограничени акаунти.',
    'sp.s1.f1': 'Обжалвания',
    'sp.s1.f2': 'Документи',
    'sp.s1.f3': 'Връзка с платформи',
    'sp.s1.f4': 'Проследяване',
    'sp.s2.title': 'Премахване на shadowban',
    'sp.s2.desc': 'Разрешаване на shadowban.',
    'sp.s2.f1': 'Диагностика',
    'sp.s2.f2': 'Одит',
    'sp.s2.f3': 'Обхват',
    'sp.s2.f4': 'Превенция',
    'sp.s3.title': 'Откраднати профили',
    'sp.s3.desc': 'Възстановяване на хакнати и откраднати профили.',
    'sp.s3.f1': 'Възстановяване',
    'sp.s3.f2': 'Сигурност',
    'sp.s3.f3': 'Доказателства',
    'sp.s3.f4': 'Превенция',
    'sp.s4.title': 'Консултация',
    'sp.s4.desc': 'Стратегия за растеж.',
    'sp.s4.f1': 'Стратегия',
    'sp.s4.f2': 'Съответствие',
    'sp.s4.f3': 'Оптимизация',
    'sp.s4.f4': 'Прегледи',
    'sp.s5.title': 'Правни документи',
    'sp.s5.desc': 'Обжалвания за сложни случаи.',
    'sp.s5.f1': 'Писма',
    'sp.s5.f2': 'Доказателства',
    'sp.s5.f3': 'Отговори',
    'sp.s5.f4': 'Ескалации',
    'sp.s6.title': 'Корпоративна защита',
    'sp.s6.desc': 'За агенции и марки.',
    'sp.s6.f1': 'Мениджър',
    'sp.s6.f2': 'Приоритет',
    'sp.s6.f3': 'Мн. акаунти',
    'sp.s6.f4': 'Кризисен',
    'sp.aud.label': 'За кого',
    'sp.aud.title': 'Кого ',
    'sp.aud.titleSpan': 'защитаваме',
    'sp.a1.title': 'Физически лица',
    'sp.a1.desc': 'Лични акаунти',
    'sp.a2.title': 'Създатели',
    'sp.a2.desc': 'Инфлуенсъри',
    'sp.a3.title': 'Публични лица',
    'sp.a3.desc': 'Политици',
    'sp.a4.title': 'Бизнеси',
    'sp.a4.desc': 'Марки',
    'sp.cta.title': 'Не сте сигурни каква услуга ви трябва?',
    'sp.cta.desc': 'Свържете се за безплатна оценка.',
    'sp.cta.btn': 'Безплатна оценка',

    // Pricing page
    'pp.hero.label': 'Цени',
    'pp.hero.title': 'Прозрачни ',
    'pp.hero.titleSpan': 'цени',
    'pp.hero.desc': 'Без скрити такси.',
    'pp.plans.title': 'Планове за възстановяване',
    'pp.plans.sub': 'Еднократна такса',
    'pp.p1.name': 'Лек казус',
    'pp.p1.desc': '250 евро',
    'pp.p1.f1': 'Свален пост',
    'pp.p1.f2': 'Намалена дистрибуция',
    'pp.p1.f3': 'Ограничаване на live и други функции',
    'pp.p1.f4': 'Shadowban',
    'pp.p2.name': 'Тежък казус',
    'pp.p2.desc': '500 евро',
    'pp.p2.badge': 'Най-популярен',
    'pp.p2.f1': 'Изтрит профил',
    'pp.p2.f2': 'Откраднат профил',
    'pp.p2.f3': 'Ограничаване на Ad Account',
    'pp.p2.f4': 'Подробна стратегия',
    'pp.p2.f5': 'Пълно съдействие',
    'pp.p2.f6': 'Постоянен мониторинг',
    'pp.p3.name': 'Еднократна консултация',
    'pp.p3.desc': '100 евро',
    'pp.p3.f1': 'Запознаване с правилата на Мета и други платформи',
    'pp.p3.f2': 'Относно вашето съдържание',
    'pp.p3.f3': 'Услугите на вашия бизнес',
    'pp.p3.f4': 'Персонализирани препоръки',
    'pp.p3.f5': 'Писмено резюме',
    'pp.p3.f6': '30 мин сесия',
    'pp.btn': 'Започни',
    'pp.guarantee.title': 'Важно',
    'pp.guarantee.desc': 'Unban Solutions не може да гарантира конкретен резултат от производството по обжалване, тъй като решенията се вземат изцяло от платформите. Гарантираме стриктно, професионално и добросъвестно изпълнение на всички действия по подготовката и воденето на всеки казус.',
    'pp.guarantee.btn': 'Свържи се с нас',

    // Process page
    'pr.hero.label': 'Процес',
    'pr.hero.title': 'Как ',
    'pr.hero.titleSpan': 'възстановяваме',
    'pr.hero.desc': 'акаунти',
    'pr.hero.sub': '4-степенна методология с техническа експертиза.',
    'pr.step1.num': '01',
    'pr.step1.title': 'Първоначална оценка',
    'pr.step1.desc': 'Цялостен анализ на статуса, ограничението и политиките.',
    'pr.step1.d1': 'Статус преглед',
    'pr.step1.d2': 'Анализ',
    'pr.step1.d3': 'Проверка',
    'pr.step1.d4': 'Оценка',
    'pr.step1.time': '24 часа',
    'pr.step2.num': '02',
    'pr.step2.title': 'Стратегия',
    'pr.step2.desc': 'Индивидуална стратегия с документи.',
    'pr.step2.d1': 'Стратегия',
    'pr.step2.d2': 'Документи',
    'pr.step2.d3': 'Доказателства',
    'pr.step2.d4': 'Канал',
    'pr.step2.time': '1-2 дни',
    'pr.step3.num': '03',
    'pr.step3.title': 'Изпълнение',
    'pr.step3.desc': 'Обжалвания с директна връзка.',
    'pr.step3.d1': 'Обжалване',
    'pr.step3.d2': 'Връзка',
    'pr.step3.d3': 'Проследяване',
    'pr.step3.d4': 'Актуализации',
    'pr.step3.time': '3-7 дни',
    'pr.step4.num': '04',
    'pr.step4.title': 'Защита',
    'pr.step4.desc': 'Защита и мониторинг след възстановяване.',
    'pr.step4.d1': 'Одит',
    'pr.step4.d2': 'Съответствие',
    'pr.step4.d3': 'Превенция',
    'pr.step4.d4': 'Мониторинг',
    'pr.step4.time': 'Постоянно',
    'pr.cta.title': 'Готови ли сте да ',
    'pr.cta.titleSpan': 'започнете',
    'pr.cta.desc': 'Безплатна оценка. Без задължения.',
    'pr.cta.btn': 'Безплатна оценка',

    // Contact page
    'cp.hero.label': 'Контакти',
    'cp.hero.title': 'Опишете ',
    'cp.hero.titleSpan': 'казуса си',
    'cp.hero.sub': '',
    'cp.hero.desc': 'Започнете с платформата и проблема. След това добавете само необходимите подробности.',
    'cp.info.title': 'Свържете се с ',
    'cp.info.titleSpan': 'нас',
    'cp.info.email': 'Имейл',
    'cp.info.phone': 'Телефон',
    'cp.info.address': 'Адрес',
    'cp.info.availability': 'Наличност',
    'cp.info.emailVal': 'support@unbansolutions.com',
    'cp.info.phoneVal': '0883 391411',
    'cp.info.addrVal': 'София',
    'cp.info.addrVal2': 'Шипченски Проход 18',
    'cp.info.availVal': 'Онлайн форма',
    'cp.info.availVal2': 'Достъпна по всяко време',
    'cp.form.name': 'Име',
    'cp.form.namePh': 'Вашето име',
    'cp.form.email': 'Имейл',
    'cp.form.emailPh': 'ваш@имейл.com',
    'cp.form.platform': 'Платформа',
    'cp.form.platformDef': 'Изберете',
    'cp.form.platformO1': 'Instagram',
    'cp.form.platformO2': 'TikTok',
    'cp.form.platformO3': 'YouTube',
    'cp.form.platformO4': 'Twitter / X',
    'cp.form.platformO5': 'Facebook',
    'cp.form.platformO6': 'LinkedIn',
    'cp.form.platformO7': 'Друга',
    'cp.form.issue': 'Проблем',
    'cp.form.issueDef': 'Изберете',
    'cp.form.issueO1': 'Баннат акаунт',
    'cp.form.issueO2': 'Спрян акаунт',
    'cp.form.issueO3': 'Shadowban',
    'cp.form.issueO4': 'Ограничени функции',
    'cp.form.issueO5': 'Хакнат акаунт',
    'cp.form.issueO6': 'Друг',
    'cp.form.message': 'Съобщение',
    'cp.form.messagePh': 'Опишете ситуацията...',
    'cp.form.files': 'Прикачени файлове',
    'cp.form.filesDesc': 'Качете известия или екранни снимки, свързани с казуса. Не изпращайте пароли или кодове за потвърждение.',
    'cp.form.filesDrop': 'Пуснете файловете тук или',
    'cp.form.filesBrowse': 'изберете',
    'cp.form.filesMax': 'Макс. 3 файла, до 3 MB всеки и 4 MB общо',
    'cp.form.submit': 'Изпрати за оценка',
    'cp.success.title': 'Изпратено!',
    'cp.success.desc': 'Ще се свържем до 24 часа.',
    'cp.emergency.title': 'Спешни казуси',
    'cp.emergency.desc': 'Приоритетно обслужване (може да включва допълнителни такси)',
    'cp.emergency.btn': 'Позвъни сега',

    // Login
    'lp.title': 'Добре дошли',
    'lp.subtitle': 'Вход в клиентския портал',
    'lp.email': 'Имейл',
    'lp.emailPh': 'ваш@имейл.com',
    'lp.password': 'Парола',
    'lp.passwordPh': 'Парола',
    'lp.submit': 'Вход',
    'lp.noAccount': 'Нямате акаунт?',
    'lp.register': 'Създайте',

    // Register
    'rp.title': 'Създай акаунт',
    'rp.subtitle': 'Клиентски портал',
    'rp.name': 'Име',
    'rp.namePh': 'Вашето име',
    'rp.email': 'Имейл',
    'rp.emailPh': 'ваш@имейл.com',
    'rp.password': 'Парола',
    'rp.passwordPh': 'Парола',
    'rp.confirm': 'Потвърди парола',
    'rp.confirmPh': 'Потвърди',
    'rp.submit': 'Създай',
    'rp.hasAccount': 'Имате акаунт?',
    'rp.login': 'Вход',

    // Legal pages
    'leg.privacy': 'Политика за ',
    'leg.privacySpan': 'поверителност',
    'leg.terms': 'Общи ',
    'leg.termsSpan': 'условия',
    'leg.payments': 'Плащания и ',
    'leg.paymentsSpan': 'възстановявания',
    'leg.label': 'Правна информация',
    'leg.date': 'Актуализирано: 19 юли 2026 г.',

    // Payments page
    'pay.methods': 'Методи на плащане',
    'pay.policy': 'Политика за възстановяване',
    'pay.full': 'Отказ преди започване',
    'pay.fullDesc': 'При валиден отказ преди започване на работата сумата се възстановява по приложимия закон и писмената оферта.',
    'pay.partial': 'Започнало изпълнение',
    'pay.partialDesc': 'При изрично поискано ранно започване може да се дължи пропорционална сума за вече извършената работа.',
    'pay.none': 'Решение на платформата',
    'pay.noneDesc': 'Отказът на платформата сам по себе си не доказва неизпълнение и не поражда автоматично право на пълно възстановяване.',

    // File upload
    'file.remove': 'Премахни',
    'file.selected': 'избрани файла',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.pricing': 'Pricing',
    'nav.process': 'Process',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.help': 'Send a Case',
    'hero.call': 'Call us',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.lang': 'BG',

    // Hero
    'hero.title': 'Is your account ',
    'hero.titleSpan': 'blocked, restricted or stolen?',
    'hero.desc': 'Send us your case. Within 24 hours, you will receive an initial assessment, realistic options and a clear next step.',
    'hero.cta1': 'Send Your Case',
    'hero.cta2': 'See How It Works',
    'hero.stat2': 'Free initial assessment',
    'hero.stat3': 'Never send passwords or codes',
    'hero.badge1': 'Professional Service',
    'hero.badge2': 'All Platforms',
    'hero.badge3': 'Clear communication',

    // Services section
    'svc.label': 'What We Do',
    'svc.title': 'Complete ',
    'svc.titleSpan': 'Protection',
    'svc.all': 'All Services',
    'svc.s1.title': 'Account Recovery',
    'svc.s1.desc': 'Banned, suspended, or restricted accounts on Instagram, TikTok, YouTube, Facebook.',
    'svc.s2.title': 'Shadowban Removal',
    'svc.s2.desc': 'Diagnosis and resolution of invisibility issues.',
    'svc.s3.title': 'Content Protection',
    'svc.s3.desc': 'Preventive audits and legal consultations.',
    'svc.s4.title': 'Emergency Response',
    'svc.s4.desc': 'Priority handling for urgent cases.',
    'svc.s5.title': 'Stolen Profiles',
    'svc.s5.desc': 'Recovery of hacked and stolen profiles.',
    'svc.s6.title': 'Legal Appeals',
    'svc.s6.desc': 'Professional document and appeal preparation.',

    // Process section
    'proc.label': 'How We Work',
    'proc.title': 'Recovery ',
    'proc.titleSpan': 'Process',
    'proc.sub': 'From a short request to a clear assessment and action plan.',
    'proc.step1': 'Processing Your Request',
    'proc.step1desc': 'Individual offer based on case complexity.',
    'proc.step2': 'Preparing Official Appeal',
    'proc.step2desc': 'Individual action plan.',
    'proc.step3': 'Sending via Official Channels',
    'proc.step3desc': 'Direct communication.',
    'proc.step4': 'Tracking Your Case',
    'proc.step4desc': 'Until resolution.',
    'proc.tag1': 'Free Assessment',
    'proc.tag2': 'Clear follow-up',
    'proc.tag3': 'Discreet Service',

    // Results section
    'res.label': 'Process',
    'res.title': 'Clear ',
    'res.titleSpan': 'parameters',
    'res.stat2': 'Typical first response',
    'res.stat3': 'Supported platforms',

    // Testimonials
    'test.label': 'Testimonials',
    'test.title': 'Built Around ',
    'test.titleSpan': 'Clients',
    'test.q1': 'They recovered our brand account in 72 hours. Incredible!',
    'test.n1': 'Maria Petrova',
    'test.t1': 'Marketing Director',
    'test.q2': 'After months of frustration, they recovered my account.',
    'test.n2': 'Ivan Stoyanov',
    'test.t2': 'Content Creator',
    'test.q3': 'Professional, fast, and discreet. Highly recommend!',
    'test.n3': 'Gergana Dimitrova',
    'test.t3': 'Online Store Owner',

    // CTA
    'cta.title': 'Tell Us What Happened',
    'cta.desc': 'A short form, no obligation and no need to share passwords. First response within 24 hours.',
    'cta.btn1': 'Send Your Case',
    'cta.btn2': 'View Pricing',

    // Footer
    'foot.desc': 'Professional assessment and assistance with digital account issues.',
    'foot.services': 'Services',
    'foot.company': 'Company',
    'foot.legal': 'Legal',
    'foot.rights': 'All rights reserved.',
    'foot.privacy': 'Privacy Policy',
    'foot.terms': 'Terms of Service',
    'foot.payments': 'Payments',
    'foot.cookies': 'Cookie settings',

    // Services page
    'sp.hero.label': 'Services',
    'sp.hero.title': 'Expert Solutions for ',
    'sp.hero.titleSpan': 'Recovery',
    'sp.hero.desc': 'From recovery to proactive protection — comprehensive solutions.',
    'sp.s1.title': 'Account Recovery',
    'sp.s1.desc': 'Banned, suspended, or restricted accounts.',
    'sp.s1.f1': 'Appeals',
    'sp.s1.f2': 'Documents',
    'sp.s1.f3': 'Platform Liaison',
    'sp.s1.f4': 'Tracking',
    'sp.s2.title': 'Shadowban Removal',
    'sp.s2.desc': 'Shadowban resolution.',
    'sp.s2.f1': 'Diagnostics',
    'sp.s2.f2': 'Audit',
    'sp.s2.f3': 'Scope',
    'sp.s2.f4': 'Prevention',
    'sp.s3.title': 'Stolen Profiles',
    'sp.s3.desc': 'Recovery of hacked and stolen profiles.',
    'sp.s3.f1': 'Recovery',
    'sp.s3.f2': 'Security',
    'sp.s3.f3': 'Evidence',
    'sp.s3.f4': 'Prevention',
    'sp.s4.title': 'Consultation',
    'sp.s4.desc': 'Growth strategy.',
    'sp.s4.f1': 'Strategy',
    'sp.s4.f2': 'Compliance',
    'sp.s4.f3': 'Optimization',
    'sp.s4.f4': 'Reviews',
    'sp.s5.title': 'Legal Documents',
    'sp.s5.desc': 'Appeals for complex cases.',
    'sp.s5.f1': 'Letters',
    'sp.s5.f2': 'Evidence',
    'sp.s5.f3': 'Responses',
    'sp.s5.f4': 'Escalations',
    'sp.s6.title': 'Corporate Protection',
    'sp.s6.desc': 'For agencies and brands.',
    'sp.s6.f1': 'Manager',
    'sp.s6.f2': 'Priority',
    'sp.s6.f3': 'Multi Accounts',
    'sp.s6.f4': 'Crisis',
    'sp.aud.label': 'For Whom',
    'sp.aud.title': 'Who We ',
    'sp.aud.titleSpan': 'Protect',
    'sp.a1.title': 'Individuals',
    'sp.a1.desc': 'Personal accounts',
    'sp.a2.title': 'Creators',
    'sp.a2.desc': 'Influencers',
    'sp.a3.title': 'Public Figures',
    'sp.a3.desc': 'Politicians',
    'sp.a4.title': 'Businesses',
    'sp.a4.desc': 'Brands',
    'sp.cta.title': 'Not sure what service you need?',
    'sp.cta.desc': 'Contact us for a free assessment.',
    'sp.cta.btn': 'Free Assessment',

    // Pricing page
    'pp.hero.label': 'Pricing',
    'pp.hero.title': 'Transparent ',
    'pp.hero.titleSpan': 'Pricing',
    'pp.hero.desc': 'No hidden fees.',
    'pp.plans.title': 'Recovery Plans',
    'pp.plans.sub': 'One-time fee',
    'pp.p1.name': 'Light Case',
    'pp.p1.desc': '250 EUR',
    'pp.p1.f1': 'Removed post',
    'pp.p1.f2': 'Reduced distribution',
    'pp.p1.f3': 'Live and other function restrictions',
    'pp.p1.f4': 'Shadowban',
    'pp.p2.name': 'Heavy Case',
    'pp.p2.desc': '500 EUR',
    'pp.p2.badge': 'Most Popular',
    'pp.p2.f1': 'Deleted profile',
    'pp.p2.f2': 'Stolen profile',
    'pp.p2.f3': 'Ad Account restriction',
    'pp.p2.f4': 'Detailed strategy',
    'pp.p2.f5': 'Full assistance',
    'pp.p2.f6': 'Ongoing monitoring',
    'pp.p3.name': 'One-time Consultation',
    'pp.p3.desc': '100 EUR',
    'pp.p3.f1': 'Understanding Meta and other platform rules',
    'pp.p3.f2': 'Regarding your content',
    'pp.p3.f3': 'Your business services',
    'pp.p3.f4': 'Personalized recommendations',
    'pp.p3.f5': 'Written summary',
    'pp.p3.f6': '30 min session',
    'pp.btn': 'Get Started',
    'pp.guarantee.title': 'Important',
    'pp.guarantee.desc': 'Unban Solutions cannot guarantee a specific result from the appeal process, as decisions are made entirely by the platforms. We guarantee strict, professional, and diligent execution of all actions in the preparation and handling of each case.',
    'pp.guarantee.btn': 'Contact Us',

    // Process page
    'pr.hero.label': 'Process',
    'pr.hero.title': 'How We ',
    'pr.hero.titleSpan': 'Recover',
    'pr.hero.desc': 'Accounts',
    'pr.hero.sub': '4-step methodology with technical expertise.',
    'pr.step1.num': '01',
    'pr.step1.title': 'Initial Assessment',
    'pr.step1.desc': 'Comprehensive analysis of status, restrictions, and policies.',
    'pr.step1.d1': 'Status Review',
    'pr.step1.d2': 'Analysis',
    'pr.step1.d3': 'Verification',
    'pr.step1.d4': 'Assessment',
    'pr.step1.time': '24 hours',
    'pr.step2.num': '02',
    'pr.step2.title': 'Strategy',
    'pr.step2.desc': 'Individual strategy with documentation.',
    'pr.step2.d1': 'Strategy',
    'pr.step2.d2': 'Documents',
    'pr.step2.d3': 'Evidence',
    'pr.step2.d4': 'Channel',
    'pr.step2.time': '1-2 days',
    'pr.step3.num': '03',
    'pr.step3.title': 'Execution',
    'pr.step3.desc': 'Appeals with direct communication.',
    'pr.step3.d1': 'Appeal',
    'pr.step3.d2': 'Communication',
    'pr.step3.d3': 'Tracking',
    'pr.step3.d4': 'Updates',
    'pr.step3.time': '3-7 days',
    'pr.step4.num': '04',
    'pr.step4.title': 'Protection',
    'pr.step4.desc': 'Protection and monitoring after recovery.',
    'pr.step4.d1': 'Audit',
    'pr.step4.d2': 'Compliance',
    'pr.step4.d3': 'Prevention',
    'pr.step4.d4': 'Monitoring',
    'pr.step4.time': 'Ongoing',
    'pr.cta.title': 'Ready to ',
    'pr.cta.titleSpan': 'Start',
    'pr.cta.desc': 'Free assessment. No obligations.',
    'pr.cta.btn': 'Free Assessment',

    // Contact page
    'cp.hero.label': 'Contact',
    'cp.hero.title': 'Describe ',
    'cp.hero.titleSpan': 'your case',
    'cp.hero.sub': '',
    'cp.hero.desc': 'Start with the platform and issue, then add only the details we need.',
    'cp.info.title': 'Get in ',
    'cp.info.titleSpan': 'Touch',
    'cp.info.email': 'Email',
    'cp.info.phone': 'Phone',
    'cp.info.address': 'Address',
    'cp.info.availability': 'Availability',
    'cp.info.emailVal': 'support@unbansolutions.com',
    'cp.info.phoneVal': '0883 391411',
    'cp.info.addrVal': 'Sofia',
    'cp.info.addrVal2': 'Shipchenski Prohod 18',
    'cp.info.availVal': 'Online form',
    'cp.info.availVal2': 'Available at any time',
    'cp.form.name': 'Name',
    'cp.form.namePh': 'Your name',
    'cp.form.email': 'Email',
    'cp.form.emailPh': 'your@email.com',
    'cp.form.platform': 'Platform',
    'cp.form.platformDef': 'Select',
    'cp.form.platformO1': 'Instagram',
    'cp.form.platformO2': 'TikTok',
    'cp.form.platformO3': 'YouTube',
    'cp.form.platformO4': 'Twitter / X',
    'cp.form.platformO5': 'Facebook',
    'cp.form.platformO6': 'LinkedIn',
    'cp.form.platformO7': 'Other',
    'cp.form.issue': 'Issue',
    'cp.form.issueDef': 'Select',
    'cp.form.issueO1': 'Banned Account',
    'cp.form.issueO2': 'Suspended Account',
    'cp.form.issueO3': 'Shadowban',
    'cp.form.issueO4': 'Restricted Features',
    'cp.form.issueO5': 'Hacked Account',
    'cp.form.issueO6': 'Other',
    'cp.form.message': 'Message',
    'cp.form.messagePh': 'Describe your situation...',
    'cp.form.files': 'Attachments',
    'cp.form.filesDesc': 'Upload notices or screenshots related to the case. Never send passwords or verification codes.',
    'cp.form.filesDrop': 'Drop files here or',
    'cp.form.filesBrowse': 'browse',
    'cp.form.filesMax': 'Max 3 files, up to 3 MB each and 4 MB total',
    'cp.form.submit': 'Send for Assessment',
    'cp.success.title': 'Sent!',
    'cp.success.desc': 'We will contact you within 24 hours.',
    'cp.emergency.title': 'Urgent Cases',
    'cp.emergency.desc': 'Priority handling (may include additional fees)',
    'cp.emergency.btn': 'Call Now',

    // Login
    'lp.title': 'Welcome',
    'lp.subtitle': 'Client Portal Login',
    'lp.email': 'Email',
    'lp.emailPh': 'your@email.com',
    'lp.password': 'Password',
    'lp.passwordPh': 'Password',
    'lp.submit': 'Login',
    'lp.noAccount': "Don't have an account?",
    'lp.register': 'Sign Up',

    // Register
    'rp.title': 'Create Account',
    'rp.subtitle': 'Client Portal',
    'rp.name': 'Name',
    'rp.namePh': 'Your name',
    'rp.email': 'Email',
    'rp.emailPh': 'your@email.com',
    'rp.password': 'Password',
    'rp.passwordPh': 'Password',
    'rp.confirm': 'Confirm Password',
    'rp.confirmPh': 'Confirm',
    'rp.submit': 'Create Account',
    'rp.hasAccount': 'Already have an account?',
    'rp.login': 'Login',

    // Legal pages
    'leg.privacy': 'Privacy ',
    'leg.privacySpan': 'Policy',
    'leg.terms': 'Terms of ',
    'leg.termsSpan': 'Service',
    'leg.payments': 'Payments & ',
    'leg.paymentsSpan': 'Refunds',
    'leg.label': 'Legal Information',
    'leg.date': 'Updated: 19 July 2026',

    // Payments page
    'pay.methods': 'Payment Methods',
    'pay.policy': 'Refund Policy',
    'pay.full': 'Withdrawal before work starts',
    'pay.fullDesc': 'A valid withdrawal before work begins is refunded under applicable law and the written offer.',
    'pay.partial': 'Performance has started',
    'pay.partialDesc': 'If early performance was expressly requested, a proportionate amount may be due for work already completed.',
    'pay.none': 'Platform decision',
    'pay.noneDesc': 'A refusal by the platform does not by itself prove non-performance or create an automatic right to a full refund.',

    // File upload
    'file.remove': 'Remove',
    'file.selected': 'selected files',
  },
};

const LanguageContext = createContext<LangCtx | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem('lang') as Lang;
    return saved === 'en' ? 'en' : 'bg';
  });

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem('lang', l);
    document.documentElement.lang = l;
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang][key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
}
