// Generates src/generated/blog-data.ts (consumed by the React pages) and
// api/blog-schedule.js (consumed by the weekly redeploy cron). Runs before
// tsc/vite in `npm run build` and `npm run dev`; the outputs are committed so
// the checkout works without a prior build, but each build regenerates them —
// that is what lets a scheduled article go live on a cron-triggered redeploy
// without a new commit.
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { loadArticles } from './blog-lib.mjs';

const { published, upcoming, all } = await loadArticles();

const toPublic = (a) => ({
  slug: a.slug,
  title: a.title,
  titleEn: a.titleEn,
  date: a.date,
  excerpt: a.excerpt,
  excerptEn: a.excerptEn,
  description: a.description,
  keywords: a.keywords,
  tags: a.tags,
  wordCount: a.wordCount,
  readTime: a.readTime,
  readTimeEn: a.readTimeEn,
  bodyHtml: a.bodyHtml,
  faq: a.faq,
});

const toTeaser = (a) => ({
  title: a.title,
  titleEn: a.titleEn,
  excerpt: a.excerpt,
  excerptEn: a.excerptEn,
  readTime: a.readTime,
  readTimeEn: a.readTimeEn,
});

const dataTs = `// AUTO-GENERATED by scripts/generate-blog.mjs — do not edit by hand.
// Source of truth: content/blog/*.md

export interface BlogFaqItem {
  question: string;
  answer: string;
  answerHtml: string;
}

export interface BlogArticle {
  slug: string;
  title: string;
  titleEn: string;
  date: string;
  excerpt: string;
  excerptEn: string;
  description: string;
  keywords: string;
  tags: string[];
  wordCount: number;
  readTime: string;
  readTimeEn: string;
  bodyHtml: string;
  faq: BlogFaqItem[];
}

export interface UpcomingArticle {
  title: string;
  titleEn: string;
  excerpt: string;
  excerptEn: string;
  readTime: string;
  readTimeEn: string;
}

export const publishedArticles: BlogArticle[] = ${JSON.stringify(published.map(toPublic), null, 2)};

export const upcomingArticles: UpcomingArticle[] = ${JSON.stringify(upcoming.map(toTeaser), null, 2)};
`;

const scheduleJs = `// AUTO-GENERATED by scripts/generate-blog.mjs — do not edit by hand.
// Publish dates of all blog articles; api/redeploy.js uses this to decide
// whether a weekly cron tick still needs to trigger a rebuild.
export const articleDates = ${JSON.stringify(all.map((a) => a.date).sort())};
`;

const generatedDir = path.join(process.cwd(), 'src', 'generated');
await mkdir(generatedDir, { recursive: true });
await writeFile(path.join(generatedDir, 'blog-data.ts'), dataTs, 'utf8');
await writeFile(path.join(process.cwd(), 'api', 'blog-schedule.js'), scheduleJs, 'utf8');

console.log(`Blog data: ${published.length} published, ${upcoming.length} upcoming.`);
